### ISSUE TITLE
Move to Multiformats?

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/haskell-multihash#3]
Hey @LukeHoersten!

Thanks so much for this. As you may know, we recently created the [Multiformats](//github.com/multiformats) organization to be a home for all of the multiformats - multiaddr, multihash, etc. Would you be interested in moving this repository to that organization? You would still have admin rights on the repository, but it would be a part of a wider organization. This would mean more relevant eyes on it (most likely) and better cross-repository issue tracking. We'd also add a line mentioning you as the original author, and of course your commits would stay the same. 

Of course, keeping it on your profile is also cool; we'll still link to this from the main multihash repository at github.com/multiformats/multihash.

Thanks for taking the time to read this. 👍 

Tracking issue, here: https://github.com/multiformats/multiformats/issues/4.

**Comment by lukehoersten** [comment]
@RichardLitt sure. Go ahead and fork it in there.

**Comment by RichardLitt** [comment]
@LukeHoersten A fork might be sub-optimal, because we'd have to keep it updated, and people may PR that fork and not this one. Would you be interested in transferring it?

**Comment by lukehoersten** [comment]
Yeah I'm willing to move it. How do I go about doing that?

**Comment by Ericson2314** [comment]
repo Settings > transfer. It's red and scary looking on purpose :).

**Comment by lukehoersten** [comment]
Looks like it's not possible without admin rights to multiformats.

**Comment by RichardLitt** [comment]
You're a member now! You'll be able to do it. I will re-add you as an admin of this repo after it is moved. :)

**Comment by lukehoersten** [comment]
I'm still getting the error "You don’t have admin rights to multiformats" when attempting to transfer.

**Comment by Ericson2314** [comment]
@RichardLitt I think one needs to be an _admin_ not member on the org side. In the past I've seen transferring the repo to an admin, who then transfers it to the org. Not atomic, but seems easy enough.

**Comment by lukehoersten** [comment]
Got it moved. I don't show up as an owner of it anymore though.

**Comment by Ericson2314** [comment]
Perhaps that sort of information is reset on move.

**Comment by RichardLitt** [comment]
Yeah; multiformats is now technically the owner. I've given you admin rights again, and opened a PR - #4 - to add a README that makes it clear you wrote, maintain, and hold the copyright for this repository. How does that sound?

**Comment by lukehoersten** [comment]
👍🏻
